version: '3.9'

networks:
  manage-tasks-network:

services:
  manage-tasks-api:
    image: ${DOCKER_REGISTRY-}managetasksapi
    container_name: manage-tasks-API
    build:
      context: .
      dockerfile: ManageTasks.API/Dockerfile
    depends_on:
      - manage-tasks-db
    networks:
      - manage-tasks-network

  manage-tasks-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: manage-tasks-DB
    hostname: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_USER=sa
      - MSSQL_SA_PASSWORD=ManageTasks__Password
    ports:
      - 8077:1433
    expose:
      - 8077
    networks:
      - manage-tasks-network
